#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 17 00:05:44 -03 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ef7c473616ae46829eec548938972e2d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot main_behav xil_defaultlib.main -log elaborate.log"
xelab -wto ef7c473616ae46829eec548938972e2d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot main_behav xil_defaultlib.main -log elaborate.log

